// OPS.Site/src/pages/Sobre.tsx
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ExternalLink, Youtube } from "lucide-react";
import { useState, useEffect } from "react";
import { fetchImportacao, ImportacaoData } from "@/lib/api";

const Sobre = () => {
  const [importacaoData, setImportacaoData] = useState<ImportacaoData[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadData = async () => {
      try {
        const data = await fetchImportacao();
        const filteredData = data.filter(item => item.sigla !== "");
        setImportacaoData(filteredData);
      } catch (error) {
        console.error('Error fetching importacao data:', error);
      } finally {
        setLoading(false);
      }
    };

    loadData();
  }, []);

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="container mx-auto px-4 py-8">
        <div className="border-b-2 border-primary pb-2 mb-8">
          <h1 className="text-2xl font-bold text-foreground">
            Conheça a Operação Política Supervisionada
          </h1>
        </div>

        {/* Videos Section */}
        <div className="grid gap-6 md:grid-cols-2 mb-12">
          <div className="aspect-video bg-muted rounded-lg overflow-hidden relative group">
            <div className="absolute inset-0 flex items-center justify-center">
              <iframe
                width="540"
                height="303.75"
                src="https://www.youtube-nocookie.com/embed/JqO0_EhbJUw"
                frameBorder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              ></iframe>
            </div>
          </div>
          <div className="aspect-video bg-muted rounded-lg overflow-hidden relative group">
            <div className="absolute inset-0 flex items-center justify-center">
              <iframe
                width="540"
                height="303.75"
                src="https://www.youtube-nocookie.com/embed/lcNf9gi2FdY"
                frameBorder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              ></iframe>
            </div>
          </div>
        </div>

        {/* Info Cards */}
        <div className="grid gap-6 md:grid-cols-2 mb-12">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">O que é a OPS?</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-sm text-muted-foreground">
              <p>
                A <strong className="text-foreground">Operação Política Supervisionada</strong> fiscaliza
                detalhadamente gastos realizados com verba pública por deputados federais, senadores e de
                deputados estaduais dos estados que possuem transparência.
              </p>
              <p>
                Até o momento a OPS proporcionou{" "}
                <a
                  href="https://institutoops.org.br/o-que-ja-fizemos/"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                ><strong className="text-primary underline">economia os cofres públicos em valor superior a R$ 6
                  milhões</strong></a>{" "}
                graças a este trabalho de fiscalização que permite exigir diretamente dos parlamentares
                a devolução dos valores indevidamente utilizados.
              </p>
              <p>
                A OPS conta com a ajuda de cidadãos espalhados pelo Brasil e exterior que ajudam
                diretamente nas fiscalizações que são realizadas, no desenvolvimento de ferramentas de
                tecnologia e no suporte financeiro que é feito por{" "}
                <a
                  href="https://institutoops.org.br/apoio/"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                ><strong className="text-primary underline">doações voluntárias</strong></a>.
              </p>
              <p>
                Apesar de ser especialista na fiscalização dos gastos com a verba indenizatória, a OPS
                também monitora contas públicas de estados e municípios, além de disponibilizar aos
                cidadãos um{" "}
                <a
                  href="https://institutoops.org.br/denunciar/"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                ><strong className="text-primary underline">canal para o recebimento de denúncias</strong></a>, anônimas ou não.
              </p>
              <p>
                A OPS é coordenada por seu fundador,{" "}
                <a href="https://institutoops.org.br/quem-somos/" target="_blank" rel="nofollow noopener noreferrer"
                ><strong className="text-primary underline">Lúcio Big</strong></a>.
              </p>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-lg">O que é CEAP?</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-sm text-muted-foreground">
              <p>
                CEAP é a sigla da <strong className="text-foreground">Cota para o Exercício da Atividade Parlamentar</strong>
                (No Senado se chama CEAPS).
              </p>
              <p>
                Trata-se de um recurso público disponível mensalmente aos deputados e senadores para o
                custeio de suas atividades parlamentares. Nos estados essa verba pode receber diversos
                outros nomes.
              </p>
              <p>
                Apesar de ser dinheiro público, fato que já implicaria no seu enquadramento à Lei de
                Licitações, o uso da verba dispensa qualquer tipo de burocracia exigida por essa lei,
                dando ao político a livre escolha da empresa a ser contratada para fornecimento do
                produto ou serviço. Há casos que nem mesmo empresas são contratadas, apenas pessoas
                físicas.
              </p>
              <p>
                Não é raro encontrar irregularidades no uso desta cota. Algumas são escandalosas, como
                locações de veículos feitas em padarias ou até de pessoas que nem sabiam possuir o
                veículo locado pelo parlamentar, até irregularidades de cunho fiscal, como a emissão
                de notas fiscais sem lastro legal.
              </p>
              <p>Veja alguns casos{" "}
                <a
                  href="https://institutoops.org.br/o-que-ja-fizemos/"
                  target="_blank"
                  rel="nofollow noopener noreferrer"
                ><strong className="text-primary underline">aqui</strong></a
                >.</p>
            </CardContent>
          </Card>
        </div>

        {/* Additional Info */}
        <div className="grid gap-6 md:grid-cols-2 mb-12">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Como posso ajudar?</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-sm text-muted-foreground">
              <p>
                Existem várias formas de contribuir com a OPS:
              </p>
              <ul className="list-disc pl-5 space-y-2">
                <li>
                  <strong className="text-foreground">Fiscalizando:</strong> Use o site para
                  verificar os gastos dos parlamentares do seu estado
                </li>
                <li>
                  <strong className="text-foreground">Denunciando:</strong> Envie denúncias de
                  irregularidades através do nosso canal de denúncias
                </li>
                <li>
                  <strong className="text-foreground">Divulgando:</strong> Compartilhe nosso trabalho
                  nas redes sociais
                </li>
                <li>
                  <strong className="text-foreground">Doando:</strong>{" "}
                  <a href="https://institutoops.org.br/apoio/" target="_blank" rel="nofollow noopener noreferrer" className="hover:underline inline-flex items-center gap-1">
                    Contribua financeiramente para manter o projeto funcionando <ExternalLink className="h-3 w-3" /></a>
                </li>
              </ul>
            </CardContent>
            <CardHeader>
              <CardTitle className="text-lg">Informações úteis para fiscalização</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-sm text-muted-foreground">
              <ol className="list-decimal pl-5 space-y-4">
                <li className="mb-3">
                  <strong className="text-foreground">Câmara de Deputados</strong>
                  <ul className="list-disc pl-5 mt-2 space-y-1">
                    <li>
                      <a
                        href="https://www2.camara.leg.br/comunicacao/assessoria-de-imprensa/guia-para-jornalistas/cota-parlamentar"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        Regras para uso da cota parlamentar (Ato da mesa Nº 43) <ExternalLink className="h-3 w-3" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="http://www.camara.gov.br/cota-parlamentar/ANEXO_ATO_DA_MESA_43_2009.pdf"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        Limites mensais por parlamentar <ExternalLink className="h-3 w-3" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="http://www.camara.gov.br/cota-parlamentar"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        Explorar a cota parlamentar na câmara <ExternalLink className="h-3 w-3" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="http://www2.camara.leg.br/deputados/pesquisa"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        Conheça os Deputados <ExternalLink className="h-3 w-3" />
                      </a>
                    </li>
                  </ul>
                </li>
                <li className="mb-3">
                  <strong className="text-foreground">Senado Federal</strong>
                  <ul className="list-disc pl-5 mt-2 space-y-1">
                    <li>
                      <a
                        href="https://adm.senado.leg.br/normas/ui/pub/normaConsultada;jsessionid=FF712C2488692EF4C9A4517976A6F3FE.tomcat-1?0&idNorma=14380751"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        Regras para uso da cota parlamentar <ExternalLink className="h-3 w-3" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="https://www12.senado.leg.br/transparencia/leg/legislacao-relacionada"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        Legislação relacionada <ExternalLink className="h-3 w-3" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="http://www25.senado.leg.br/web/transparencia/sen"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        Explorar a cota parlamentar no senado <ExternalLink className="h-3 w-3" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="http://www25.senado.leg.br/web/senadores"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        Conheça os senadores <ExternalLink className="h-3 w-3" />
                      </a>
                    </li>
                  </ul>
                </li>
              </ol>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Transparência</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4 text-sm text-muted-foreground">
              <p>
                A OPS preza pela total transparência em suas ações. Todos os dados utilizados são
                provenientes de fontes oficiais e públicas:
              </p>
              <ol className="list-decimal pl-5 space-y-4">
                <li className="mb-3">
                  <strong className="text-foreground">Câmara de Deputados</strong>
                  <br />
                  <ul className="list-disc pl-5 mt-2 space-y-1">
                    <li>
                      <a
                        href="https://www.camara.leg.br/transparencia/gastos-parlamentares"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        Cota parlamentar <ExternalLink className="h-3 w-3" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="https://dadosabertos.camara.leg.br/"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        Dados Abertos <ExternalLink className="h-3 w-3" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="https://www.camara.leg.br/deputados/quem-sao"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        Conheça os Deputados <ExternalLink className="h-3 w-3" />
                      </a>
                    </li>
                  </ul>
                </li>
                <li className="mb-3">
                  <strong className="text-foreground">Senado Federal</strong>
                  <br />
                  <ul className="list-disc pl-5 mt-2 space-y-1">
                    <li>
                      <a
                        href="https://www12.senado.leg.br/dados-abertos/conjuntos?portal=Administrativo&grupo=senadores"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        Cota parlamentar (CSV) <ExternalLink className="h-3 w-3" />
                      </a>
                    </li>
                    <li>
                      <a
                        href="https://www25.senado.leg.br/web/senadores/em-exercicio"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        Conheça os Senadores <ExternalLink className="h-3 w-3" />
                      </a>
                    </li>
                  </ul>
                </li>
                <li className="mb-3">
                  <strong className="text-foreground">Assembleias Legislativas</strong>
                  {(() => {
                    if (loading) {
                      return <div className="mt-2 text-muted-foreground">Carregando dados das assembleias legislativas...</div>;
                    }
                    
                    if (importacaoData.length > 0) {
                      return (
                        <div className="mt-2 overflow-x-auto">
                          <table className="w-full text-sm">
                            <thead>
                              <tr className="border-b">
                                <th className="text-left py-2 px-2">Assembleia</th>
                                <th className="text-left py-2 px-2">Última Despesa</th>
                                <th className="text-left py-2 px-2">Última Importação</th>
                              </tr>
                            </thead>
                            <tbody>
                              {importacaoData.map((item) => (
                                <tr key={item.id} className="border-b hover:bg-muted/50">
                                  <td className="py-2 px-2">
                                    <a 
                                      href={item.url} 
                                      target="_blank" 
                                      rel="nofollow noopener noreferrer" 
                                      className="text-primary hover:underline inline-flex items-center gap-1"
                                    >
                                      {item.nome} {item.sigla && <>({item.sigla})</>} <ExternalLink className="h-3 w-3" />
                                    </a>
                                    {item.info && <div className="text-muted-foreground text-xs mt-1">* {item.info}</div>}
                                  </td>
                                  <td className="py-2 px-2 text-muted-foreground">
                                    {item.ultima_despesa || '-'}
                                  </td>
                                  <td className="py-2 px-2 text-muted-foreground">
                                    {item.ultima_importacao || '-'}
                                  </td>
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      );
                    }
                    
                    return <div className="mt-2 text-muted-foreground">Nenhum dado disponível no momento.</div>;
                  })()}
                </li>
                <li className="mb-3">
                  <strong className="text-foreground">Fornecedores</strong>
                  <ul className="list-disc pl-5 mt-2 space-y-1">
                    <li>
                      <a
                        href="http://www.receita.fazenda.gov.br/pessoajuridica/cnpj/cnpjreva/cnpjreva_solicitacao.asp"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1"
                      >
                        Receita Federal <ExternalLink className="h-3 w-3" />
                      </a>{" "}
                      (via
                      <a
                        href="https://minhareceita.org"
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        className="text-primary hover:underline inline-flex items-center gap-1 ml-1"
                      >
                        Minha Receita <ExternalLink className="h-3 w-3" />
                      </a>
                      )
                    </li>
                  </ul>
                </li>
              </ol>
            </CardContent>
          </Card>
        </div>

        {/* Contact Section */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Entre em Contato</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4 text-sm text-muted-foreground">
            <p>
              Dúvidas, sugestões ou denúncias? Entre em contato conosco através dos nossos canais:
            </p>
            <div className="flex flex-wrap gap-4">
              <a href="https://institutoops.org.br/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline inline-flex items-center gap-1">
                Instituto OPS <ExternalLink className="h-3 w-3" />
              </a>
              <a href="mailto:contato@ops.org.br" className="text-primary hover:underline">
                contato@ops.org.br
              </a>
              <a href="https://twitter.com/LucioBig" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline inline-flex items-center gap-1">
                Twitter <ExternalLink className="h-3 w-3" />
              </a>
              <a href="https://www.facebook.com/institutoops" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline inline-flex items-center gap-1">
                Facebook <ExternalLink className="h-3 w-3" />
              </a>
              <a href="https://www.youtube.com/channel/UCfQ98EX3oOv6IHBdUNMJq8Q" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline inline-flex items-center gap-1">
                YouTube <ExternalLink className="h-3 w-3" />
              </a>
              <a href="https://github.com/ops-org/operacao-politica-supervisionada" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline inline-flex items-center gap-1">
                Github <ExternalLink className="h-3 w-3" />
              </a>
            </div>
          </CardContent>
        </Card>
      </main >
      <Footer />
    </div >
  );
};

export default Sobre;

// OPS.UI/src/components/sobre.vue
<template>
  <div class="container" id="sobre-page">
    <br />
    <div id="info-geral">
      <h3 class="media-heading page-title">Conheça a Operação Política Supervisionada</h3>
      <br />
      <div class="row">
        <div class="col-md-6">
          <div class="form-group text-center">
            <iframe
              width="540"
              height="303.75"
              src="https://www.youtube-nocookie.com/embed/JqO0_EhbJUw"
              frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen
            ></iframe>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group text-center">
            <iframe
              width="540"
              height="303.75"
              src="https://www.youtube-nocookie.com/embed/lcNf9gi2FdY"
              frameborder="0"
              allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
              allowfullscreen
            ></iframe>
          </div>
        </div>
      </div>
      <br />
      <div class="row">
        <div class="col-md-6">
          <div class="card mb-3">
            <div class="card-header bg-light">O que é a OPS?</div>
            <div class="card-body">
              <p class="text-justify style2">
                A
                <strong>Operação Política Supervisionada</strong> fiscaliza de forma detalhada os gastos realizados via CEAP ou CEAPS. Até o momento já foram economizados quase R$ 6 milhões do dinheiro público graças a estas fiscalizações e às exigências feitas diretamente aos parlamentares para que devolvam o dinheiro público indevidamente utilizado.
              </p>
              <p
                class="text-justify style2"
              >A OPS conta com a ajuda de seus colaboradores, espalhados pelo Brasil, para o levantamento de informações necessárias para a conclusão de fiscalizações, como por exemplo, o envio de fotos de endereços suspeitos em diversas cidades do país. Além disso, qualquer um pode ser um fiscal dos gastos públicos e este site oferece dados suficientes para isso.</p>
              <p
                class="text-justify style2"
              >Apesar de ser especialista na fiscalização dos gastos com a verba indenizatória, a OPS também aceita denúncias de outros setores públicos, dando a elas o destino certo para que sejam apuradas pelas autoridades competentes.</p>
              <p class="text-justify style2">
                O trabalho de fiscalização, coordenado por seu fundador,
                <a
                  href="https://luciobig.com.br"
                  target="_blank"
                >Lúcio Big</a>, é realizado voluntariamente por diversas pessoas Brasil afora.
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card mb-3">
            <div class="card-header bg-light">O que é CEAP?</div>
            <div class="card-body">
              <p class="text-justify style2">
                CEAP é a sigla da
                <strong>Cota para o Exercício da Atividade Parlamentar</strong> (No Senado se chama CEAPS).
              </p>
              <p
                class="text-justify style2"
              >Trata-se de um recurso público disponível mensalmente aos deputados e senadores para o custeio de suas atividades parlamentares.</p>
              <p
                class="text-justify style2"
              >Apesar de ser dinheiro público, fato que já implicaria no seu enquadramento à Lei Nº 8.666, o uso da verba dispensa qualquer tipo de burocracia exigida pela lei de licitações, dando ao deputado e ao senador a livre escolha da empresa a ser contratada para fornecimento do produto ou serviço.</p>
              <p
                class="text-justify style2"
              >Não é raro encontrar irregularidades escandalosas, como locações de veículos feitas em padarias ou cópias de trabalhos escolares transformados em «pareceres jurídicos» generosamente pagos com o dinheiro do contribuinte.</p>
            </div>
          </div>
        </div>
         <div class="col-md-6">
          <div class="card mb-3">
            <div class="card-header bg-light mb-3">Origem das Informações</div>
            <ol>
              <li class="mb-3">
                <strong>Câmara de Deputados</strong>
                <br />
                <ul>
                  <li>
                    <a
                      href="http://www2.camara.leg.br/transparencia/cota-para-exercicio-da-atividade-parlamentar/dados-abertos-cota-parlamentar"
                      target="_blank"
                      rel="nofollow"
                    >Cota parlamentar (XML)</a>
                  </li>
                  <li>
                    <a
                      href="http://www.camara.leg.br/sitcamaraws/deputados.asmx"
                      target="_blank"
                      rel="nofollow"
                    >Dados abertos (WebService)</a>
                  </li>
                </ul>
              </li>
              <li class="mb-3">
                <strong>Senado Federal</strong>
                <br />
                <ul>
                  <li>
                    <a
                      href="https://www12.senado.leg.br/transparencia/dados-abertos/dados-abertos-ceaps"
                      target="_blank"
                      rel="nofollow"
                    >Cota parlamentar (CSV)</a>
                  </li>
                  <li>
                    <a
                      href="http://legis.senado.leg.br/dadosabertos/docs/index.html"
                      target="_blank"
                      rel="nofollow"
                    >Dados abertos (WebService)</a>
                  </li>
                  <li>
                    <a
                      href="http://www.senado.gov.br/transparencia/dadosAbertos/dadosAbertos.asp"
                      target="_blank"
                      rel="nofollow"
                    >Dados abertos (CSV)</a>
                  </li>
                </ul>
              </li>
              <li class="mb-3">
                <strong>Informações dos Beneficiários</strong>
                <ul>
                  <li>
                    <a
                      href="http://www.receita.fazenda.gov.br/pessoajuridica/cnpj/cnpjreva/cnpjreva_solicitacao.asp"
                      target="_blank"
                      rel="nofollow"
                    >Receita Federal</a>
                  </li>
                </ul>
              </li>
            </ol>
          </div>
          <div class="card mb-3">
            <div class="card-header bg-light mb-3">Informações úteis</div>
            <ol>
              <li class="mb-3">
                <strong>Câmara de Deputados</strong>
                <ul>
                  <li>
                    <a
                      href="http://www2.camara.leg.br/legin/int/atomes/2009/atodamesa-43-21-maio-2009-588364-normaatualizada-cd-mesa.html"
                      target="_blank"
                      rel="nofollow"
                    >Regras para uso da cota parlamentar (Ato da mesa Nº 43)</a>
                  </li>
                  <li>
                    <a
                      href="http://www2.camara.leg.br/participe/fale-conosco/perguntas-frequentes/cota-para-o-exercicio-da-atividade-parlamentar"
                      target="_blank"
                      rel="nofollow"
                    >Legislação relacionada</a>
                  </li>
                  <li>
                    <a
                      href="http://www.camara.gov.br/cota-parlamentar/ANEXO_ATO_DA_MESA_43_2009.pdf"
                      target="_blank"
                      rel="nofollow"
                    >Limites mensais por parlamentar</a>
                  </li>
                  <li>
                    <a
                      href="http://www.camara.gov.br/cota-parlamentar"
                      target="_blank"
                      rel="nofollow"
                    >Explorar a cota parlamentar na câmara</a>
                  </li>
                  <li>
                    <a
                      href="http://www2.camara.leg.br/deputados/pesquisa"
                      target="_blank"
                      rel="nofollow"
                    >Conheça os Deputados</a>
                  </li>
                </ul>
              </li>
              <li class="mb-3">
                <strong>Senado Federal</strong>
                <ul>
                  <li>
                    <a
                      href="https://www12.senado.leg.br/transparencia/leg/pdf/normas/APS-5-2014-compilado.pdf"
                      target="_blank"
                      rel="nofollow"
                    >Regras para uso da cota parlamentar</a>
                  </li>
                  <li>
                    <a
                      href="https://www12.senado.leg.br/transparencia/leg/legislacao-relacionada"
                      target="_blank"
                      rel="nofollow"
                    >Legislação relacionada</a>
                  </li>
                  <li>
                    <a
                      href="http://www25.senado.leg.br/web/transparencia/sen"
                      target="_blank"
                      rel="nofollow"
                    >Explorar a cota parlamentar no senado</a>
                  </li>
                  <li>
                    <a
                      href="http://www25.senado.leg.br/web/senadores"
                      target="_blank"
                      rel="nofollow"
                    >Conheça os senadores</a>
                  </li>
                </ul>
              </li>
            </ol>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card mb-3">
            <div class="card-header bg-light">Contribua</div>
            <div class="card-body">
              <p>
                <strong>Com divulgação</strong>
              </p>
              <p>Divulgue o projeto para seus amigos e contatos.</p>

              <p>
                <strong>Com análises</strong>
              </p>
              <p
                class="text-justify"
              >Você pode reportar suspeitas sobre quaisquer transações. Contribua detalhando qualquer movimentação ou padrão suspeito.</p>

              <p>
                <strong>Com código</strong>
              </p>
              <p
                class="text-justify"
              >Esse é um projeto de código aberto, você pode contribuir com correções e novas funcionalidades.</p>
              <p>
                <a
                  href="https://github.com/ops-org/operacao-politica-supervisionada"
                  target="_blank"
                >https://github.com/ops-org/operacao-politica-supervisionada</a>
              </p>

              <p>
                <strong>Com ideias</strong>
              </p>
              <p
                class="text-justify"
              >Qualquer ideia contrutiva é sempre bem vinda. Também é possivel votar nas ideias existentes e deixar sua opinião.</p>
              <p>
                <a
                  href="https://feedback.userreport.com/9cf4c59a-d438-48b0-aa5e-e16f549b9c8c/#ideas/popular"
                  target="_blank"
                >Deixar uma ideia</a>
              </p>

              <p>
                <strong>Com doações</strong>
              </p>
              <p
                class="text-justify"
              >Você poderá doar uma única vez ou programar para que suas doações sejam mensais. É possível cancelar as doações recorrentes a qualquer momento, sem pagamento de taxas ou multas.</p>
              <a
                target="_blank"
                href="https://sites.google.com/site/doandoparaaops/doacao-via-deposito---banco-do-brasil"
              >
                <img
                  src="https://luciobigdotcomdotbr.files.wordpress.com/2015/11/bb_100.png?w=100"
                  alt="bb"
                  width="96"
                  height="56"
                />
              </a>
              <a target="_blank" href="https://www.patreon.com/bePatron?patAmt=20&amp;u=192467">
                <img
                  src="https://luciobigdotcomdotbr.files.wordpress.com/2015/11/patreon_25.png?w=100"
                  alt="patreon"
                  width="96"
                  height="56"
                />
              </a>
              <a
                target="_blank"
                href="https://sites.google.com/site/doandoparaaops/doacao-mensal-paypal"
              >
                <img
                  src="https://luciobigdotcomdotbr.files.wordpress.com/2015/11/paypal_25.png?w=100"
                  alt="paypal"
                  width="96"
                  height="56"
                />
              </a>
              <a
                target="_blank"
                href="https://pagseguro.uol.com.br/checkout/nc/nl/donation/sender-identification.jhtml?t=b71889bbdc400e71008fab3d4ba4802662561764f8d69f10#rmcl"
              >
                <img
                  src="https://luciobigdotcomdotbr.files.wordpress.com/2015/11/pagseguro_25.png?w=100"
                  alt="pagseguro"
                  width="96"
                  height="56"
                />
              </a>
              <a target="_blank" href="https://apoia.se/ops">
                <img
                  src="https://luciobigdotcomdotbr.files.wordpress.com/2015/11/apo.png?w=100"
                  alt="apoia.se"
                  width="96"
                  height="56"
                />
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <br />
    <div style="padding-bottom: 10px;">
      <p class="text-right">
        <a href="https://luciobig.com.br/o-que-e-ops/" target="_blank" class="btn btn-light btn-sm">
          Saiba mais sobre a OPS&nbsp;
          <i class="fa fa-chevron-right"></i>
        </a>
      </p>
    </div>
  </div>
</template>
